name: Deploy Docusaurus & Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Environment Variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "OWNER=${{ secrets.OWNER }}" >> $GITHUB_ENV
          echo "REPO=${{ secrets.REPO }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # ✅ Install Backend Dependencies
      - name: Install Backend Dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./server

      # ✅ Start Backend Server (`server.mjs`)
      - name: Start Backend Server
        run: |
          node --experimental-modules server.mjs &
          sleep 10  # Wait for the server to start
        working-directory: ./server

      # ✅ Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: npm ci --legacy-peer-deps

      # ✅ Build the Frontend (Docusaurus)
      - name: Build Docusaurus
        run: npm run build

      # ✅ Upload Build Artifact for Deployment
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build  

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
